version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "assignment"
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -uroot -p123
      timeout: 20s
      retries: 10
    command: mysqld --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: